--CREATE SEQUENCE LOCATION_SEQ;

CREATE OR REPLACE TRIGGER LOCATION_ID_TRIG 
BEFORE INSERT ON LOCATIONS
FOR EACH ROW

BEGIN
  SELECT LOCATION_SEQ.NEXTVAL
  INTO   :new.LOCATION_id
  FROM   dual;
END;

CREATE OR REPLACE TRIGGER USER_ID_TRIG 
BEFORE INSERT ON USERS
FOR EACH ROW

BEGIN
  SELECT USER_SEQ.NEXTVAL
  INTO   :new.USER_id
  FROM   dual;
END;
